import { scheduleReload, hasPendingReload } from './updateGate';

/**
 * Service worker registration with silent, gated updates.
 *
 * We register the workbox worker (generated by vite-plugin-pwa) directly
 * rather than through workbox-window: that wrapper treats any update found
 * more than 60s after page load as "external" and never reloads for it, which
 * is exactly the midday-deploy case we care about.
 *
 * Flow: poll registration.update() -> new worker reaches "installed" (waiting)
 * -> updateGate waits for an idle moment -> SKIP_WAITING -> controllerchange
 * -> reload. Guest state is in localStorage, so the reload is invisible.
 */

// How often an open app asks the server whether a new build exists. Browsers
// only check on navigation (or every 24h), which never happens in a standalone
// PWA that stays open all day.
const CHECK_INTERVAL_MS = 60 * 1000;

// Caches left behind by the hand-written service worker used for the first
// event. Harmless, but they hold tens of MB on returning guests' phones.
const LEGACY_CACHE_PREFIXES = ['shire-passport-'];

async function clearLegacyCaches() {
  if (!('caches' in window)) return;
  try {
    const keys = await caches.keys();
    await Promise.all(
      keys
        .filter((key) => LEGACY_CACHE_PREFIXES.some((prefix) => key.startsWith(prefix)))
        .map((key) => caches.delete(key))
    );
  } catch {
    // Best-effort cleanup.
  }
}

export function registerServiceWorker() {
  // eslint-disable-next-line no-undef
  window.__BUILD_ID__ = typeof __BUILD_ID__ !== 'undefined' ? __BUILD_ID__ : 'dev';
  console.log(`Checkins build ${window.__BUILD_ID__}`);

  if (!('serviceWorker' in navigator)) return;
  if (!import.meta.env.PROD) return;

  clearLegacyCaches();

  let reloadWhenControlled = false;
  let reloading = false;

  // Fires once the waiting worker has taken over. Reload exactly once.
  navigator.serviceWorker.addEventListener('controllerchange', () => {
    if (!reloadWhenControlled || reloading) return;
    reloading = true;
    window.location.reload();
  });

  const onWorkerWaiting = (worker) => {
    // New build fully downloaded. Swap it in the next time the guest is idle.
    scheduleReload(() => {
      reloadWhenControlled = true;
      worker.postMessage({ type: 'SKIP_WAITING' });
    });
  };

  const watchInstalling = (registration) => {
    const worker = registration.installing;
    if (!worker) return;
    worker.addEventListener('statechange', () => {
      // "installed" with an existing controller means "waiting behind the
      // current worker". Without a controller it's the very first install.
      if (worker.state === 'installed' && navigator.serviceWorker.controller) {
        onWorkerWaiting(worker);
      }
    });
  };

  window.addEventListener('load', async () => {
    let registration;
    try {
      registration = await navigator.serviceWorker.register('/sw.js', { scope: '/' });
    } catch (error) {
      console.warn('Service worker registration failed:', error);
      return;
    }

    // A worker may already be waiting from a previous visit.
    if (registration.waiting && navigator.serviceWorker.controller) {
      onWorkerWaiting(registration.waiting);
    }
    watchInstalling(registration);
    registration.addEventListener('updatefound', () => watchInstalling(registration));

    const check = () => {
      if (navigator.onLine === false) return;
      registration.update().catch(() => {});
    };

    setInterval(check, CHECK_INTERVAL_MS);
    document.addEventListener('visibilitychange', () => {
      if (document.visibilityState === 'visible') check();
    });
    window.addEventListener('focus', check);
    window.addEventListener('online', check);

    // Console helpers for debugging on a guest's phone.
    window.__checkinsUpdate = { check, registration, hasPendingReload };
  });
}
