import { useState, useRef, useEffect } from 'react';

// Emoji data with searchable names
const EMOJI_DATA = {
  'Smileys': [
    ['😀', 'grinning face happy smile'],
    ['😃', 'grinning face big eyes happy smile'],
    ['😄', 'grinning face smiling eyes happy'],
    ['😁', 'beaming face smiling eyes grin'],
    ['😆', 'grinning squinting face laugh'],
    ['😅', 'grinning face sweat nervous'],
    ['🤣', 'rolling floor laughing rofl lol'],
    ['😂', 'face tears joy crying laughing lol'],
    ['🙂', 'slightly smiling face'],
    ['😊', 'smiling face smiling eyes blush happy'],
    ['😇', 'smiling face halo angel innocent'],
    ['🥰', 'smiling face hearts love'],
    ['😍', 'smiling face heart eyes love'],
    ['🤩', 'star struck excited amazed'],
    ['😘', 'face blowing kiss love'],
    ['😗', 'kissing face'],
    ['😚', 'kissing face closed eyes'],
    ['😋', 'face savoring food yum delicious tongue'],
    ['😛', 'face tongue out'],
    ['😜', 'winking face tongue'],
    ['🤪', 'zany face crazy wild'],
    ['😝', 'squinting face tongue'],
    ['🤑', 'money mouth face rich dollar'],
    ['🤗', 'hugging face hug'],
    ['🤭', 'face hand over mouth giggle oops'],
    ['🤫', 'shushing face quiet secret'],
    ['🤔', 'thinking face hmm wonder'],
    ['🤐', 'zipper mouth face secret quiet'],
    ['🤨', 'face raised eyebrow suspicious'],
    ['😐', 'neutral face meh'],
    ['😑', 'expressionless face'],
    ['😶', 'face without mouth silent'],
    ['😏', 'smirking face smug'],
    ['😒', 'unamused face annoyed'],
    ['🙄', 'face rolling eyes'],
    ['😬', 'grimacing face awkward nervous'],
    ['🤥', 'lying face pinocchio'],
    ['😌', 'relieved face peaceful'],
    ['😔', 'pensive face sad'],
    ['😪', 'sleepy face tired'],
    ['🤤', 'drooling face'],
    ['😴', 'sleeping face zzz'],
    ['😷', 'face medical mask sick'],
    ['🤒', 'face thermometer sick fever'],
    ['🤕', 'face head bandage hurt injured'],
    ['🤢', 'nauseated face sick gross'],
    ['🤮', 'face vomiting sick throw up'],
    ['🤧', 'sneezing face sick'],
    ['🥵', 'hot face sweating heat'],
    ['🥶', 'cold face freezing frozen'],
    ['🥴', 'woozy face drunk dizzy'],
    ['😵', 'dizzy face'],
    ['🤯', 'exploding head mind blown shocked'],
    ['🤠', 'cowboy hat face'],
    ['🥳', 'partying face celebration birthday'],
    ['🥸', 'disguised face glasses mustache'],
    ['😎', 'smiling face sunglasses cool'],
    ['🤓', 'nerd face glasses geek'],
    ['🧐', 'face monocle fancy'],
    ['😕', 'confused face'],
    ['😟', 'worried face'],
    ['🙁', 'slightly frowning face sad'],
    ['😮', 'face open mouth surprised'],
    ['😯', 'hushed face'],
    ['😲', 'astonished face shocked'],
    ['😳', 'flushed face embarrassed'],
    ['🥺', 'pleading face puppy eyes'],
    ['😦', 'frowning face open mouth'],
    ['😧', 'anguished face'],
    ['😨', 'fearful face scared'],
    ['😰', 'anxious face sweat worried'],
    ['😥', 'sad relieved face'],
    ['😢', 'crying face tear sad'],
    ['😭', 'loudly crying face sobbing'],
    ['😱', 'face screaming fear scared'],
    ['😖', 'confounded face'],
    ['😣', 'persevering face'],
    ['😞', 'disappointed face sad'],
    ['😓', 'downcast face sweat'],
    ['😩', 'weary face tired'],
    ['😫', 'tired face exhausted'],
    ['🥱', 'yawning face sleepy tired'],
    ['😤', 'face steam nose angry'],
    ['😡', 'pouting face angry mad'],
    ['😠', 'angry face mad'],
    ['🤬', 'face symbols mouth cursing swearing'],
    ['😈', 'smiling face horns devil'],
    ['👿', 'angry face horns devil'],
    ['💀', 'skull dead death'],
    ['☠️', 'skull crossbones dead death pirate'],
    ['💩', 'pile poo poop'],
    ['🤡', 'clown face'],
    ['👹', 'ogre monster'],
    ['👺', 'goblin monster'],
    ['👻', 'ghost spooky halloween'],
    ['👽', 'alien ufo extraterrestrial'],
    ['👾', 'alien monster space invader game'],
    ['🤖', 'robot face'],
    ['😺', 'grinning cat'],
    ['😸', 'grinning cat smiling eyes'],
    ['😹', 'cat tears joy'],
    ['😻', 'smiling cat heart eyes love'],
    ['😼', 'cat wry smile'],
    ['😽', 'kissing cat'],
    ['🙀', 'weary cat'],
    ['😿', 'crying cat'],
    ['😾', 'pouting cat'],
  ],
  'Gestures': [
    ['👋', 'waving hand hello bye wave'],
    ['🤚', 'raised back hand'],
    ['🖐️', 'hand fingers splayed'],
    ['✋', 'raised hand stop high five'],
    ['🖖', 'vulcan salute spock'],
    ['👌', 'ok hand okay'],
    ['🤌', 'pinched fingers italian'],
    ['🤏', 'pinching hand small tiny'],
    ['✌️', 'victory hand peace'],
    ['🤞', 'crossed fingers luck'],
    ['🤟', 'love you gesture hand'],
    ['🤘', 'sign horns rock metal'],
    ['🤙', 'call me hand shaka'],
    ['👈', 'backhand index pointing left'],
    ['👉', 'backhand index pointing right'],
    ['👆', 'backhand index pointing up'],
    ['🖕', 'middle finger'],
    ['👇', 'backhand index pointing down'],
    ['☝️', 'index pointing up'],
    ['👍', 'thumbs up like good yes'],
    ['👎', 'thumbs down dislike bad no'],
    ['✊', 'raised fist power'],
    ['👊', 'oncoming fist bump punch'],
    ['🤛', 'left facing fist bump'],
    ['🤜', 'right facing fist bump'],
    ['👏', 'clapping hands applause'],
    ['🙌', 'raising hands celebration hooray'],
    ['👐', 'open hands'],
    ['🤲', 'palms up together'],
    ['🤝', 'handshake deal agreement'],
    ['🙏', 'folded hands pray please thanks namaste'],
    ['✍️', 'writing hand'],
    ['💪', 'flexed biceps strong muscle'],
    ['🦾', 'mechanical arm robot prosthetic'],
    ['🦿', 'mechanical leg robot prosthetic'],
    ['🦵', 'leg'],
    ['🦶', 'foot'],
    ['👂', 'ear listen hearing'],
    ['🦻', 'ear hearing aid'],
    ['👃', 'nose smell'],
    ['🧠', 'brain mind think'],
    ['🫀', 'anatomical heart organ'],
    ['🫁', 'lungs breathing organ'],
    ['🦷', 'tooth teeth dental'],
    ['🦴', 'bone skeleton'],
    ['👀', 'eyes looking see'],
    ['👁️', 'eye see look'],
    ['👅', 'tongue taste lick'],
    ['👄', 'mouth lips kiss'],
  ],
  'People': [
    ['👶', 'baby infant'],
    ['🧒', 'child kid'],
    ['👦', 'boy male child'],
    ['👧', 'girl female child'],
    ['🧑', 'person adult'],
    ['👱', 'person blond hair'],
    ['👨', 'man male adult'],
    ['🧔', 'man beard'],
    ['👩', 'woman female adult'],
    ['🧓', 'older person elder'],
    ['👴', 'old man grandpa grandfather'],
    ['👵', 'old woman grandma grandmother'],
    ['👮', 'police officer cop'],
    ['🕵️', 'detective spy sleuth'],
    ['💂', 'guard royal'],
    ['🥷', 'ninja stealth'],
    ['👷', 'construction worker builder'],
    ['🤴', 'prince royal'],
    ['👸', 'princess royal'],
    ['👳', 'person turban'],
    ['👲', 'person skullcap'],
    ['🧕', 'woman headscarf hijab'],
    ['🤵', 'person tuxedo groom'],
    ['👰', 'person veil bride wedding'],
    ['🤰', 'pregnant woman expecting'],
    ['🤱', 'breast feeding baby nursing'],
    ['👼', 'baby angel cherub'],
    ['🎅', 'santa claus christmas'],
    ['🤶', 'mrs claus christmas'],
    ['🦸', 'superhero hero'],
    ['🦹', 'supervillain villain'],
    ['🧙', 'mage wizard witch magic'],
    ['🧚', 'fairy magical'],
    ['🧛', 'vampire dracula'],
    ['🧜', 'merperson mermaid merman'],
    ['🧝', 'elf fantasy'],
    ['🧞', 'genie magic lamp'],
    ['🧟', 'zombie undead'],
    ['💆', 'person getting massage spa'],
    ['💇', 'person getting haircut'],
    ['🚶', 'person walking pedestrian'],
    ['🧍', 'person standing'],
    ['🧎', 'person kneeling'],
    ['🏃', 'person running runner jogging'],
    ['💃', 'woman dancing dancer'],
    ['🕺', 'man dancing disco'],
    ['👯', 'people bunny ears dancing'],
    ['🧖', 'person steamy room sauna spa'],
    ['🧗', 'person climbing rock'],
    ['🤸', 'person cartwheeling gymnastics'],
    ['🏌️', 'person golfing golf'],
    ['🏇', 'horse racing jockey'],
    ['⛷️', 'skier skiing snow'],
    ['🏂', 'snowboarder snowboarding'],
    ['🏋️', 'person lifting weights gym'],
    ['🤼', 'people wrestling'],
    ['🤽', 'person playing water polo'],
    ['🤾', 'person playing handball'],
    ['🤺', 'person fencing sword'],
    ['⛹️', 'person bouncing ball basketball'],
    ['🏊', 'person swimming swimmer'],
    ['🚣', 'person rowing boat'],
    ['🧘', 'person lotus position yoga meditation'],
    ['🛀', 'person taking bath bathtub'],
    ['🛌', 'person bed sleeping'],
  ],
  'Animals': [
    ['🐶', 'dog face puppy'],
    ['🐱', 'cat face kitty'],
    ['🐭', 'mouse face'],
    ['🐹', 'hamster face'],
    ['🐰', 'rabbit face bunny'],
    ['🦊', 'fox face'],
    ['🐻', 'bear face'],
    ['🐼', 'panda face'],
    ['🐻‍❄️', 'polar bear'],
    ['🐨', 'koala'],
    ['🐯', 'tiger face'],
    ['🦁', 'lion face'],
    ['🐮', 'cow face'],
    ['🐷', 'pig face'],
    ['🐸', 'frog face'],
    ['🐵', 'monkey face'],
    ['🙈', 'see no evil monkey'],
    ['🙉', 'hear no evil monkey'],
    ['🙊', 'speak no evil monkey'],
    ['🐒', 'monkey'],
    ['🐔', 'chicken'],
    ['🐧', 'penguin'],
    ['🐦', 'bird'],
    ['🐤', 'baby chick'],
    ['🐣', 'hatching chick'],
    ['🐥', 'front facing baby chick'],
    ['🦆', 'duck'],
    ['🦅', 'eagle bird'],
    ['🦉', 'owl bird'],
    ['🦇', 'bat'],
    ['🐺', 'wolf'],
    ['🐗', 'boar pig'],
    ['🐴', 'horse face'],
    ['🦄', 'unicorn magical'],
    ['🐝', 'honeybee bee'],
    ['🪱', 'worm'],
    ['🐛', 'bug caterpillar'],
    ['🦋', 'butterfly'],
    ['🐌', 'snail'],
    ['🐞', 'lady beetle ladybug'],
    ['🐜', 'ant'],
    ['🪰', 'fly insect'],
    ['🪲', 'beetle bug'],
    ['🪳', 'cockroach bug'],
    ['🦟', 'mosquito'],
    ['🦗', 'cricket insect'],
    ['🕷️', 'spider'],
    ['🦂', 'scorpion'],
    ['🐢', 'turtle tortoise'],
    ['🐍', 'snake'],
    ['🦎', 'lizard'],
    ['🦖', 'trex dinosaur'],
    ['🦕', 'dinosaur sauropod'],
    ['🐙', 'octopus'],
    ['🦑', 'squid'],
    ['🦐', 'shrimp'],
    ['🦞', 'lobster'],
    ['🦀', 'crab'],
    ['🐡', 'blowfish puffer'],
    ['🐠', 'tropical fish'],
    ['🐟', 'fish'],
    ['🐬', 'dolphin'],
    ['🐳', 'spouting whale'],
    ['🐋', 'whale'],
    ['🦈', 'shark'],
    ['🐊', 'crocodile alligator'],
    ['🐅', 'tiger'],
    ['🐆', 'leopard'],
    ['🦓', 'zebra'],
    ['🦍', 'gorilla ape'],
    ['🦧', 'orangutan ape'],
    ['🦣', 'mammoth elephant'],
    ['🐘', 'elephant'],
    ['🦛', 'hippopotamus hippo'],
    ['🦏', 'rhinoceros rhino'],
    ['🐪', 'camel dromedary'],
    ['🐫', 'two hump camel bactrian'],
    ['🦒', 'giraffe'],
    ['🦘', 'kangaroo'],
    ['🦬', 'bison buffalo'],
    ['🐃', 'water buffalo'],
    ['🐂', 'ox'],
    ['🐄', 'cow'],
    ['🐎', 'horse'],
    ['🐖', 'pig'],
    ['🐏', 'ram sheep'],
    ['🐑', 'ewe sheep'],
    ['🦙', 'llama alpaca'],
    ['🐐', 'goat'],
    ['🦌', 'deer'],
    ['🐕', 'dog'],
    ['🐩', 'poodle dog'],
    ['🦮', 'guide dog'],
    ['🐕‍🦺', 'service dog'],
    ['🐈', 'cat'],
    ['🐈‍⬛', 'black cat'],
    ['🪶', 'feather'],
    ['🐓', 'rooster chicken'],
    ['🦃', 'turkey'],
    ['🦤', 'dodo bird'],
    ['🦚', 'peacock'],
    ['🦜', 'parrot'],
    ['🦢', 'swan'],
    ['🦩', 'flamingo'],
    ['🕊️', 'dove peace bird'],
    ['🐇', 'rabbit bunny'],
    ['🦝', 'raccoon'],
    ['🦨', 'skunk'],
    ['🦡', 'badger'],
    ['🦫', 'beaver'],
    ['🦦', 'otter'],
    ['🦥', 'sloth'],
    ['🐁', 'mouse'],
    ['🐀', 'rat'],
    ['🐿️', 'chipmunk squirrel'],
    ['🦔', 'hedgehog'],
  ],
  'Food': [
    ['🍎', 'red apple fruit'],
    ['🍐', 'pear fruit'],
    ['🍊', 'tangerine orange fruit'],
    ['🍋', 'lemon citrus fruit'],
    ['🍌', 'banana fruit'],
    ['🍉', 'watermelon fruit'],
    ['🍇', 'grapes fruit'],
    ['🍓', 'strawberry fruit berry'],
    ['🫐', 'blueberries fruit berry'],
    ['🍈', 'melon fruit'],
    ['🍒', 'cherries fruit'],
    ['🍑', 'peach fruit'],
    ['🥭', 'mango fruit'],
    ['🍍', 'pineapple fruit'],
    ['🥥', 'coconut'],
    ['🥝', 'kiwi fruit'],
    ['🍅', 'tomato'],
    ['🍆', 'eggplant aubergine'],
    ['🥑', 'avocado'],
    ['🥦', 'broccoli vegetable'],
    ['🥬', 'leafy green vegetable lettuce'],
    ['🥒', 'cucumber pickle'],
    ['🌶️', 'hot pepper chili spicy'],
    ['🫑', 'bell pepper'],
    ['🌽', 'corn maize'],
    ['🥕', 'carrot vegetable'],
    ['🫒', 'olive'],
    ['🧄', 'garlic'],
    ['🧅', 'onion'],
    ['🥔', 'potato'],
    ['🍠', 'roasted sweet potato'],
    ['🥐', 'croissant bread french'],
    ['🥯', 'bagel bread'],
    ['🍞', 'bread loaf'],
    ['🥖', 'baguette bread french'],
    ['🥨', 'pretzel'],
    ['🧀', 'cheese wedge'],
    ['🥚', 'egg'],
    ['🍳', 'cooking fried egg breakfast'],
    ['🧈', 'butter'],
    ['🥞', 'pancakes breakfast'],
    ['🧇', 'waffle breakfast'],
    ['🥓', 'bacon breakfast meat'],
    ['🥩', 'cut meat steak'],
    ['🍗', 'poultry leg chicken drumstick'],
    ['🍖', 'meat bone'],
    ['🦴', 'bone'],
    ['🌭', 'hot dog frankfurter'],
    ['🍔', 'hamburger burger cheeseburger'],
    ['🍟', 'french fries chips'],
    ['🍕', 'pizza slice'],
    ['🫓', 'flatbread'],
    ['🥪', 'sandwich sub'],
    ['🥙', 'stuffed flatbread pita falafel'],
    ['🧆', 'falafel'],
    ['🌮', 'taco mexican'],
    ['🌯', 'burrito wrap mexican'],
    ['🫔', 'tamale mexican'],
    ['🥗', 'green salad'],
    ['🥘', 'shallow pan food paella'],
    ['🫕', 'fondue'],
    ['🥫', 'canned food'],
    ['🍝', 'spaghetti pasta noodles'],
    ['🍜', 'steaming bowl noodles ramen pho'],
    ['🍲', 'pot food stew'],
    ['🍛', 'curry rice'],
    ['🍣', 'sushi japanese'],
    ['🍱', 'bento box japanese'],
    ['🥟', 'dumpling'],
    ['🦪', 'oyster'],
    ['🍤', 'fried shrimp tempura'],
    ['🍙', 'rice ball onigiri'],
    ['🍚', 'cooked rice'],
    ['🍘', 'rice cracker'],
    ['🍥', 'fish cake narutomaki'],
    ['🥠', 'fortune cookie'],
    ['🥮', 'moon cake'],
    ['🍢', 'oden'],
    ['🍡', 'dango'],
    ['🍧', 'shaved ice'],
    ['🍨', 'ice cream'],
    ['🍦', 'soft ice cream cone'],
    ['🥧', 'pie dessert'],
    ['🧁', 'cupcake muffin'],
    ['🍰', 'shortcake cake dessert'],
    ['🎂', 'birthday cake celebration'],
    ['🍮', 'custard pudding flan'],
    ['🍭', 'lollipop candy'],
    ['🍬', 'candy sweet'],
    ['🍫', 'chocolate bar'],
    ['🍿', 'popcorn movie'],
    ['🍩', 'doughnut donut'],
    ['🍪', 'cookie biscuit'],
    ['🌰', 'chestnut'],
    ['🥜', 'peanuts'],
    ['🍯', 'honey pot'],
    ['🥛', 'glass milk'],
    ['🍼', 'baby bottle'],
    ['🫖', 'teapot'],
    ['☕', 'hot beverage coffee tea'],
    ['🍵', 'teacup tea'],
    ['🧃', 'beverage box juice'],
    ['🥤', 'cup straw soda drink'],
    ['🧋', 'bubble tea boba'],
    ['🍶', 'sake'],
    ['🍺', 'beer mug'],
    ['🍻', 'clinking beer mugs cheers'],
    ['🥂', 'clinking glasses champagne toast cheers'],
    ['🍷', 'wine glass'],
    ['🥃', 'tumbler glass whiskey'],
    ['🍸', 'cocktail glass martini'],
    ['🍹', 'tropical drink'],
    ['🧉', 'mate'],
    ['🍾', 'bottle popping cork champagne celebration'],
    ['🧊', 'ice cube'],
  ],
  'Activities': [
    ['⚽', 'soccer ball football'],
    ['🏀', 'basketball'],
    ['🏈', 'american football'],
    ['⚾', 'baseball'],
    ['🥎', 'softball'],
    ['🎾', 'tennis'],
    ['🏐', 'volleyball'],
    ['🏉', 'rugby football'],
    ['🥏', 'flying disc frisbee'],
    ['🎱', 'pool billiards 8 ball'],
    ['🪀', 'yo yo'],
    ['🏓', 'ping pong table tennis'],
    ['🏸', 'badminton'],
    ['🏒', 'ice hockey'],
    ['🏑', 'field hockey'],
    ['🥍', 'lacrosse'],
    ['🏏', 'cricket game'],
    ['🪃', 'boomerang'],
    ['🥅', 'goal net'],
    ['⛳', 'flag hole golf'],
    ['🪁', 'kite'],
    ['🏹', 'bow arrow archery'],
    ['🎣', 'fishing pole'],
    ['🤿', 'diving mask snorkel'],
    ['🥊', 'boxing glove'],
    ['🥋', 'martial arts uniform karate'],
    ['🎽', 'running shirt'],
    ['🛹', 'skateboard'],
    ['🛼', 'roller skate'],
    ['🛷', 'sled'],
    ['⛸️', 'ice skate'],
    ['🥌', 'curling stone'],
    ['🎿', 'skis skiing'],
    ['⛷️', 'skier'],
    ['🏂', 'snowboarder'],
    ['🪂', 'parachute skydiving'],
    ['🏋️', 'person lifting weights gym'],
    ['🤼', 'wrestlers wrestling'],
    ['🤸', 'person cartwheeling'],
    ['⛹️', 'person bouncing ball'],
    ['🤺', 'person fencing'],
    ['🤾', 'person playing handball'],
    ['🏌️', 'person golfing'],
    ['🏇', 'horse racing'],
    ['🧘', 'person lotus position yoga'],
    ['🏄', 'person surfing surfer'],
    ['🏊', 'person swimming'],
    ['🤽', 'person playing water polo'],
    ['🚣', 'person rowing boat'],
    ['🧗', 'person climbing'],
    ['🚵', 'person mountain biking'],
    ['🚴', 'person biking cycling'],
    ['🏆', 'trophy winner champion'],
    ['🥇', 'first place medal gold'],
    ['🥈', 'second place medal silver'],
    ['🥉', 'third place medal bronze'],
    ['🏅', 'sports medal'],
    ['🎖️', 'military medal'],
    ['🏵️', 'rosette'],
    ['🎗️', 'reminder ribbon'],
    ['🎫', 'ticket'],
    ['🎟️', 'admission tickets'],
    ['🎪', 'circus tent'],
    ['🤹', 'person juggling'],
    ['🎭', 'performing arts theater drama masks'],
    ['🩰', 'ballet shoes dance'],
    ['🎨', 'artist palette paint art'],
    ['🎬', 'clapper board movie film'],
    ['🎤', 'microphone karaoke singing'],
    ['🎧', 'headphone music'],
    ['🎼', 'musical score'],
    ['🎹', 'musical keyboard piano'],
    ['🥁', 'drum'],
    ['🪘', 'long drum'],
    ['🎷', 'saxophone'],
    ['🎺', 'trumpet'],
    ['🪗', 'accordion'],
    ['🎸', 'guitar'],
    ['🪕', 'banjo'],
    ['🎻', 'violin'],
    ['🎲', 'game die dice'],
    ['♟️', 'chess pawn'],
    ['🎯', 'direct hit bullseye target darts'],
    ['🎳', 'bowling'],
    ['🎮', 'video game controller gaming'],
    ['🎰', 'slot machine gambling casino'],
    ['🧩', 'puzzle piece jigsaw'],
  ],
  'Travel': [
    ['🚗', 'automobile car'],
    ['🚕', 'taxi cab'],
    ['🚙', 'sport utility vehicle suv'],
    ['🚌', 'bus'],
    ['🚎', 'trolleybus'],
    ['🏎️', 'racing car'],
    ['🚓', 'police car'],
    ['🚑', 'ambulance'],
    ['🚒', 'fire engine truck'],
    ['🚐', 'minibus van'],
    ['🛻', 'pickup truck'],
    ['🚚', 'delivery truck'],
    ['🚛', 'articulated lorry semi truck'],
    ['🚜', 'tractor farm'],
    ['🛴', 'kick scooter'],
    ['🚲', 'bicycle bike'],
    ['🛵', 'motor scooter'],
    ['🏍️', 'motorcycle'],
    ['🚨', 'police car light siren'],
    ['🚔', 'oncoming police car'],
    ['🚍', 'oncoming bus'],
    ['🚘', 'oncoming automobile'],
    ['🚖', 'oncoming taxi'],
    ['🚡', 'aerial tramway'],
    ['🚠', 'mountain cableway'],
    ['🚟', 'suspension railway'],
    ['🚃', 'railway car'],
    ['🚋', 'tram car'],
    ['🚞', 'mountain railway'],
    ['🚝', 'monorail'],
    ['🚄', 'high speed train'],
    ['🚅', 'bullet train'],
    ['🚈', 'light rail'],
    ['🚂', 'locomotive train'],
    ['🚆', 'train'],
    ['🚇', 'metro subway'],
    ['🚊', 'tram'],
    ['🚉', 'station'],
    ['✈️', 'airplane plane'],
    ['🛫', 'airplane departure takeoff'],
    ['🛬', 'airplane arrival landing'],
    ['🛩️', 'small airplane'],
    ['💺', 'seat'],
    ['🛰️', 'satellite'],
    ['🚀', 'rocket space'],
    ['🛸', 'flying saucer ufo'],
    ['🚁', 'helicopter'],
    ['🛶', 'canoe kayak'],
    ['⛵', 'sailboat'],
    ['🚤', 'speedboat'],
    ['🛥️', 'motor boat'],
    ['🛳️', 'passenger ship cruise'],
    ['⛴️', 'ferry'],
    ['🚢', 'ship'],
    ['⚓', 'anchor'],
    ['⛽', 'fuel pump gas station'],
    ['🚧', 'construction'],
    ['🚦', 'traffic light'],
    ['🚥', 'horizontal traffic light'],
    ['🚏', 'bus stop'],
    ['🗺️', 'world map'],
    ['🗿', 'moai statue easter island'],
    ['🗽', 'statue liberty new york'],
    ['🗼', 'tokyo tower'],
    ['🏰', 'castle european'],
    ['🏯', 'japanese castle'],
    ['🏟️', 'stadium'],
    ['🎡', 'ferris wheel'],
    ['🎢', 'roller coaster'],
    ['🎠', 'carousel horse'],
    ['⛲', 'fountain'],
    ['⛱️', 'umbrella ground beach'],
    ['🏖️', 'beach umbrella'],
    ['🏝️', 'desert island'],
    ['🏜️', 'desert'],
    ['🌋', 'volcano'],
    ['⛰️', 'mountain'],
    ['🏔️', 'snow capped mountain'],
    ['🗻', 'mount fuji'],
    ['🏕️', 'camping tent'],
    ['⛺', 'tent camping'],
    ['🏠', 'house building home'],
    ['🏡', 'house garden home'],
    ['🏘️', 'houses'],
    ['🏚️', 'derelict house abandoned'],
    ['🏗️', 'building construction'],
    ['🏭', 'factory'],
    ['🏢', 'office building'],
    ['🏬', 'department store'],
    ['🏣', 'japanese post office'],
    ['🏤', 'post office'],
    ['🏥', 'hospital'],
    ['🏦', 'bank'],
    ['🏨', 'hotel'],
    ['🏪', 'convenience store'],
    ['🏫', 'school'],
    ['🏩', 'love hotel'],
    ['💒', 'wedding chapel church'],
    ['🏛️', 'classical building'],
    ['⛪', 'church'],
    ['🕌', 'mosque'],
    ['🕍', 'synagogue'],
    ['🛕', 'hindu temple'],
    ['🕋', 'kaaba'],
    ['⛩️', 'shinto shrine'],
    ['🌅', 'sunrise'],
    ['🌄', 'sunrise mountains'],
    ['🌠', 'shooting star'],
    ['🎇', 'sparkler firework'],
    ['🎆', 'fireworks'],
    ['🌇', 'sunset'],
    ['🌆', 'cityscape dusk'],
    ['🏙️', 'cityscape'],
    ['🌃', 'night stars'],
    ['🌌', 'milky way galaxy'],
    ['🌉', 'bridge night'],
    ['🌁', 'foggy'],
  ],
  'Objects': [
    ['⌚', 'watch time'],
    ['📱', 'mobile phone smartphone'],
    ['📲', 'mobile phone arrow'],
    ['💻', 'laptop computer'],
    ['⌨️', 'keyboard'],
    ['🖥️', 'desktop computer'],
    ['🖨️', 'printer'],
    ['🖱️', 'computer mouse'],
    ['🕹️', 'joystick gaming'],
    ['💽', 'computer disk minidisc'],
    ['💾', 'floppy disk save'],
    ['💿', 'optical disk cd'],
    ['📀', 'dvd'],
    ['📷', 'camera'],
    ['📸', 'camera flash'],
    ['📹', 'video camera'],
    ['🎥', 'movie camera film'],
    ['📽️', 'film projector'],
    ['📞', 'telephone receiver'],
    ['☎️', 'telephone'],
    ['📟', 'pager'],
    ['📠', 'fax machine'],
    ['📺', 'television tv'],
    ['📻', 'radio'],
    ['🎙️', 'studio microphone'],
    ['🎚️', 'level slider'],
    ['🎛️', 'control knobs'],
    ['🧭', 'compass'],
    ['⏱️', 'stopwatch'],
    ['⏲️', 'timer clock'],
    ['⏰', 'alarm clock'],
    ['🕰️', 'mantelpiece clock'],
    ['⌛', 'hourglass done'],
    ['⏳', 'hourglass not done'],
    ['📡', 'satellite antenna'],
    ['🔋', 'battery'],
    ['🔌', 'electric plug'],
    ['💡', 'light bulb idea'],
    ['🔦', 'flashlight'],
    ['🕯️', 'candle'],
    ['💸', 'money wings flying'],
    ['💵', 'dollar banknote money'],
    ['💴', 'yen banknote money'],
    ['💶', 'euro banknote money'],
    ['💷', 'pound banknote money'],
    ['🪙', 'coin'],
    ['💰', 'money bag'],
    ['💳', 'credit card'],
    ['💎', 'gem stone diamond jewel'],
    ['⚖️', 'balance scale'],
    ['🧰', 'toolbox'],
    ['🔧', 'wrench tool'],
    ['🔨', 'hammer tool'],
    ['⚒️', 'hammer pick'],
    ['🛠️', 'hammer wrench tools'],
    ['⛏️', 'pick'],
    ['🔩', 'nut bolt'],
    ['⚙️', 'gear cog'],
    ['🔫', 'pistol gun water'],
    ['💣', 'bomb'],
    ['🧨', 'firecracker dynamite'],
    ['🔪', 'kitchen knife'],
    ['🗡️', 'dagger sword'],
    ['⚔️', 'crossed swords'],
    ['🛡️', 'shield'],
    ['🔮', 'crystal ball fortune'],
    ['📿', 'prayer beads'],
    ['🧿', 'nazar amulet evil eye'],
    ['💈', 'barber pole'],
    ['⚗️', 'alembic chemistry'],
    ['🔭', 'telescope'],
    ['🔬', 'microscope science'],
    ['🩹', 'adhesive bandage band aid'],
    ['🩺', 'stethoscope doctor'],
    ['💊', 'pill medicine'],
    ['💉', 'syringe injection vaccine'],
    ['🧬', 'dna genetics'],
    ['🦠', 'microbe virus bacteria germ'],
    ['🧫', 'petri dish'],
    ['🧪', 'test tube science'],
    ['🌡️', 'thermometer temperature'],
    ['🧹', 'broom'],
    ['🧺', 'basket'],
    ['🧻', 'roll paper toilet'],
    ['🚽', 'toilet'],
    ['🚿', 'shower'],
    ['🛁', 'bathtub'],
    ['🧼', 'soap'],
    ['🧽', 'sponge'],
    ['🧴', 'lotion bottle'],
    ['🔑', 'key'],
    ['🗝️', 'old key'],
    ['🚪', 'door'],
    ['🪑', 'chair'],
    ['🛋️', 'couch lamp sofa'],
    ['🛏️', 'bed'],
    ['🧸', 'teddy bear'],
    ['🖼️', 'framed picture'],
    ['🛍️', 'shopping bags'],
    ['🛒', 'shopping cart'],
    ['🎁', 'wrapped gift present'],
    ['🎈', 'balloon party'],
    ['🎏', 'carp streamer'],
    ['🎀', 'ribbon bow'],
    ['🪄', 'magic wand'],
    ['🎊', 'confetti ball'],
    ['🎉', 'party popper tada celebration'],
    ['🎎', 'japanese dolls'],
    ['🏮', 'red paper lantern'],
    ['🎐', 'wind chime'],
    ['🧧', 'red envelope'],
    ['✉️', 'envelope mail'],
    ['📩', 'envelope arrow'],
    ['📨', 'incoming envelope'],
    ['📧', 'e mail email'],
    ['💌', 'love letter'],
    ['📥', 'inbox tray'],
    ['📤', 'outbox tray'],
    ['📦', 'package box'],
    ['🏷️', 'label tag'],
    ['📪', 'mailbox closed'],
    ['📫', 'mailbox closed flag'],
    ['📬', 'mailbox open flag'],
    ['📭', 'mailbox open'],
    ['📮', 'postbox'],
    ['📯', 'postal horn'],
    ['📜', 'scroll'],
    ['📃', 'page curl'],
    ['📄', 'page facing up document'],
    ['📑', 'bookmark tabs'],
    ['🧾', 'receipt'],
    ['📊', 'bar chart'],
    ['📈', 'chart increasing'],
    ['📉', 'chart decreasing'],
    ['📆', 'tear off calendar'],
    ['📅', 'calendar'],
    ['📇', 'card index'],
    ['🗃️', 'card file box'],
    ['🗳️', 'ballot box'],
    ['🗄️', 'file cabinet'],
    ['📋', 'clipboard'],
    ['📁', 'file folder'],
    ['📂', 'open file folder'],
    ['📰', 'newspaper'],
    ['📓', 'notebook'],
    ['📔', 'notebook decorative cover'],
    ['📒', 'ledger'],
    ['📕', 'closed book'],
    ['📗', 'green book'],
    ['📘', 'blue book'],
    ['📙', 'orange book'],
    ['📚', 'books'],
    ['📖', 'open book'],
    ['🔖', 'bookmark'],
    ['🔗', 'link'],
    ['📎', 'paperclip'],
    ['🖇️', 'linked paperclips'],
    ['📐', 'triangular ruler'],
    ['📏', 'straight ruler'],
    ['🧮', 'abacus'],
    ['📌', 'pushpin'],
    ['📍', 'round pushpin pin location'],
    ['✂️', 'scissors'],
    ['🖊️', 'pen'],
    ['🖋️', 'fountain pen'],
    ['✒️', 'black nib'],
    ['🖌️', 'paintbrush'],
    ['🖍️', 'crayon'],
    ['📝', 'memo note'],
    ['✏️', 'pencil'],
    ['🔍', 'magnifying glass search'],
    ['🔎', 'magnifying glass right'],
    ['🔏', 'locked pen'],
    ['🔐', 'locked key'],
    ['🔒', 'locked'],
    ['🔓', 'unlocked'],
  ],
  'Symbols': [
    ['❤️', 'red heart love'],
    ['🧡', 'orange heart'],
    ['💛', 'yellow heart'],
    ['💚', 'green heart'],
    ['💙', 'blue heart'],
    ['💜', 'purple heart'],
    ['🖤', 'black heart'],
    ['🤍', 'white heart'],
    ['🤎', 'brown heart'],
    ['💔', 'broken heart'],
    ['❣️', 'heart exclamation'],
    ['💕', 'two hearts'],
    ['💞', 'revolving hearts'],
    ['💓', 'beating heart'],
    ['💗', 'growing heart'],
    ['💖', 'sparkling heart'],
    ['💘', 'heart arrow cupid'],
    ['💝', 'heart ribbon'],
    ['💟', 'heart decoration'],
    ['☮️', 'peace symbol'],
    ['✝️', 'latin cross'],
    ['☪️', 'star crescent'],
    ['🕉️', 'om'],
    ['☸️', 'wheel dharma'],
    ['✡️', 'star david'],
    ['🔯', 'six pointed star'],
    ['🕎', 'menorah'],
    ['☯️', 'yin yang'],
    ['☦️', 'orthodox cross'],
    ['🛐', 'place worship'],
    ['⛎', 'ophiuchus'],
    ['♈', 'aries zodiac'],
    ['♉', 'taurus zodiac'],
    ['♊', 'gemini zodiac'],
    ['♋', 'cancer zodiac'],
    ['♌', 'leo zodiac'],
    ['♍', 'virgo zodiac'],
    ['♎', 'libra zodiac'],
    ['♏', 'scorpio zodiac'],
    ['♐', 'sagittarius zodiac'],
    ['♑', 'capricorn zodiac'],
    ['♒', 'aquarius zodiac'],
    ['♓', 'pisces zodiac'],
    ['🆔', 'id button'],
    ['⚛️', 'atom symbol'],
    ['☢️', 'radioactive'],
    ['☣️', 'biohazard'],
    ['📴', 'mobile phone off'],
    ['📳', 'vibration mode'],
    ['🆚', 'vs button versus'],
    ['💯', 'hundred points 100'],
    ['🔅', 'dim button'],
    ['🔆', 'bright button'],
    ['⚠️', 'warning'],
    ['🚸', 'children crossing'],
    ['🔱', 'trident emblem'],
    ['⚜️', 'fleur de lis'],
    ['🔰', 'japanese symbol beginner'],
    ['♻️', 'recycling symbol'],
    ['✅', 'check mark button'],
    ['❌', 'cross mark x'],
    ['❎', 'cross mark button'],
    ['➕', 'plus sign'],
    ['➖', 'minus sign'],
    ['➗', 'division sign'],
    ['✖️', 'multiply x'],
    ['♾️', 'infinity'],
    ['❓', 'question mark'],
    ['❔', 'white question mark'],
    ['❕', 'white exclamation mark'],
    ['❗', 'exclamation mark'],
    ['‼️', 'double exclamation mark'],
    ['⁉️', 'exclamation question mark'],
    ['⭕', 'hollow red circle'],
    ['🛑', 'stop sign'],
    ['⛔', 'no entry'],
    ['🚫', 'prohibited'],
    ['💢', 'anger symbol'],
    ['♨️', 'hot springs'],
    ['🚷', 'no pedestrians'],
    ['🚯', 'no littering'],
    ['🚳', 'no bicycles'],
    ['🚱', 'non potable water'],
    ['🔞', 'no one under eighteen'],
    ['📵', 'no mobile phones'],
    ['🚭', 'no smoking'],
    ['🔴', 'red circle'],
    ['🟠', 'orange circle'],
    ['🟡', 'yellow circle'],
    ['🟢', 'green circle'],
    ['🔵', 'blue circle'],
    ['🟣', 'purple circle'],
    ['⚫', 'black circle'],
    ['⚪', 'white circle'],
    ['🟤', 'brown circle'],
    ['🔺', 'red triangle pointed up'],
    ['🔻', 'red triangle pointed down'],
    ['🔸', 'small orange diamond'],
    ['🔹', 'small blue diamond'],
    ['🔶', 'large orange diamond'],
    ['🔷', 'large blue diamond'],
    ['🔳', 'white square button'],
    ['🔲', 'black square button'],
    ['▪️', 'black small square'],
    ['▫️', 'white small square'],
    ['◾', 'black medium small square'],
    ['◽', 'white medium small square'],
    ['◼️', 'black medium square'],
    ['◻️', 'white medium square'],
    ['⬛', 'black large square'],
    ['⬜', 'white large square'],
    ['🟥', 'red square'],
    ['🟧', 'orange square'],
    ['🟨', 'yellow square'],
    ['🟩', 'green square'],
    ['🟦', 'blue square'],
    ['🟪', 'purple square'],
    ['🟫', 'brown square'],
    ['🔈', 'speaker low volume'],
    ['🔇', 'muted speaker'],
    ['🔉', 'speaker medium volume'],
    ['🔊', 'speaker high volume'],
    ['🔔', 'bell notification'],
    ['🔕', 'bell slash'],
    ['📣', 'megaphone'],
    ['📢', 'loudspeaker'],
    ['💬', 'speech balloon'],
    ['💭', 'thought balloon'],
    ['🗯️', 'right anger bubble'],
    ['♠️', 'spade suit'],
    ['♣️', 'club suit'],
    ['♥️', 'heart suit'],
    ['♦️', 'diamond suit'],
    ['🃏', 'joker'],
    ['🎴', 'flower playing cards'],
    ['🀄', 'mahjong red dragon'],
    ['🔃', 'clockwise vertical arrows'],
    ['🔄', 'counterclockwise arrows button'],
    ['🔙', 'back arrow'],
    ['🔚', 'end arrow'],
    ['🔛', 'on arrow'],
    ['🔜', 'soon arrow'],
    ['🔝', 'top arrow'],
    ['🎵', 'musical note'],
    ['🎶', 'musical notes'],
    ['➡️', 'right arrow'],
    ['⬅️', 'left arrow'],
    ['⬆️', 'up arrow'],
    ['⬇️', 'down arrow'],
    ['↗️', 'up right arrow'],
    ['↘️', 'down right arrow'],
    ['↙️', 'down left arrow'],
    ['↖️', 'up left arrow'],
    ['↕️', 'up down arrow'],
    ['↔️', 'left right arrow'],
    ['↩️', 'right arrow curving left'],
    ['↪️', 'left arrow curving right'],
    ['⤴️', 'right arrow curving up'],
    ['⤵️', 'right arrow curving down'],
    ['🔀', 'shuffle tracks button'],
    ['🔁', 'repeat button'],
    ['🔂', 'repeat single button'],
    ['▶️', 'play button'],
    ['⏩', 'fast forward button'],
    ['⏭️', 'next track button'],
    ['⏯️', 'play pause button'],
    ['◀️', 'reverse button'],
    ['⏪', 'fast reverse button'],
    ['⏮️', 'last track button'],
    ['🔼', 'upwards button'],
    ['⏫', 'fast up button'],
    ['🔽', 'downwards button'],
    ['⏬', 'fast down button'],
    ['⏸️', 'pause button'],
    ['⏹️', 'stop button'],
    ['⏺️', 'record button'],
    ['⏏️', 'eject button'],
    ['✔️', 'check mark'],
    ['☑️', 'check box check'],
    ['🔘', 'radio button'],
    ['🔗', 'link'],
    ['➰', 'curly loop'],
    ['➿', 'double curly loop'],
    ['〰️', 'wavy dash'],
    ['©️', 'copyright'],
    ['®️', 'registered'],
    ['™️', 'trade mark'],
  ],
};

const categories = Object.keys(EMOJI_DATA);

export default function EmojiPicker({ value, onChange, onClose }) {
  const [search, setSearch] = useState('');
  const containerRef = useRef(null);
  const categoryRefs = useRef({});

  // Close picker when clicking outside
  useEffect(() => {
    const handleClickOutside = (e) => {
      if (containerRef.current && !containerRef.current.contains(e.target)) {
        onClose();
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [onClose]);

  const scrollToCategory = (category, e) => {
    e.preventDefault();
    e.stopPropagation();
    categoryRefs.current[category]?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };

  const handleEmojiClick = (emoji, e) => {
    e.preventDefault();
    e.stopPropagation();
    onChange(emoji);
    onClose();
  };

  // Filter emojis by search term
  const getFilteredData = () => {
    if (!search) return EMOJI_DATA;

    const searchLower = search.toLowerCase();
    const results = [];

    for (const [category, emojis] of Object.entries(EMOJI_DATA)) {
      for (const [emoji, keywords] of emojis) {
        if (keywords.toLowerCase().includes(searchLower)) {
          results.push([emoji, keywords]);
        }
      }
    }

    return results.length > 0 ? { 'Results': results } : { 'Results': [] };
  };

  const filteredData = getFilteredData();

  return (
    <div
      ref={containerRef}
      className="bg-white rounded-lg shadow-xl border border-gray-200 w-80 max-h-96 flex flex-col"
      onClick={(e) => e.stopPropagation()}
    >
      {/* Search */}
      <div className="p-2 border-b border-gray-100">
        <input
          type="text"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Search emoji... (pizza, smile, heart)"
          className="w-full px-3 py-1.5 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          autoFocus
          onClick={(e) => e.stopPropagation()}
        />
      </div>

      {/* Category jump links */}
      {!search && (
        <div className="flex gap-1 p-2 border-b border-gray-100 overflow-x-auto flex-shrink-0">
          {categories.map(cat => (
            <button
              key={cat}
              type="button"
              onClick={(e) => scrollToCategory(cat, e)}
              className="px-2 py-1 text-xs rounded whitespace-nowrap hover:bg-gray-100 text-gray-600 transition-colors"
            >
              {cat}
            </button>
          ))}
        </div>
      )}

      {/* All emojis with category headers */}
      <div className="flex-1 overflow-y-auto p-2">
        {Object.entries(filteredData).map(([category, emojis]) => (
          <div key={category} ref={el => categoryRefs.current[category] = el}>
            <h4 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2 mt-2 first:mt-0">
              {category}
            </h4>
            <div className="grid grid-cols-8 gap-1 mb-2">
              {emojis.map(([emoji, keywords], i) => (
                <button
                  key={`${emoji}-${i}`}
                  type="button"
                  onClick={(e) => handleEmojiClick(emoji, e)}
                  title={keywords}
                  className={`w-8 h-8 flex items-center justify-center text-xl hover:bg-gray-100 rounded transition-colors ${
                    value === emoji ? 'bg-blue-100' : ''
                  }`}
                >
                  {emoji}
                </button>
              ))}
            </div>
          </div>
        ))}
        {search && filteredData['Results']?.length === 0 && (
          <p className="text-sm text-gray-400 text-center py-4">No emoji found for "{search}"</p>
        )}
      </div>
    </div>
  );
}
